import React from 'react'
import Aside from '@/components/Dashboard/Aside'
import Footer from '@/components/Dashboard/Footer'
import Header from '@/components/Dashboard/Header'
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Hills of Glory | Dashboard",
  // description: "Generated by create next app",
};

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <main className="flex bg-[#f1f1f1]">
      <Aside />
      <div className='w-full bg-black/60'>
        <Header />
        {children}
        <Footer />
      </div>
    </main>
  )
}

export default Layout